FILE( APPEND ${ILCSOFT_PATH}/init_ilcsoft.sh  "###########################\n" )
FILE( APPEND ${ILCSOFT_PATH}/init_ilcsoft.sh  "#\t ${name}\n" )
FILE( APPEND ${ILCSOFT_PATH}/init_ilcsoft.sh  "###########################\n" )
FILE( APPEND ${ILCSOFT_PATH}/init_ilcsoft.sh  "export ${name}_DIR=${targetdir}\n" )
	IF( EXISTS "${targetdir}/bin" AND IS_DIRECTORY "${targetdir}/bin")
FILE( APPEND ${ILCSOFT_PATH}/init_ilcsoft.sh  "export PATH=\${PATH}:${targetdir}/bin\n" )
	ENDIF()
	IF( EXISTS "${targetdir}/lib" AND IS_DIRECTORY "${targetdir}/lib")
FILE( APPEND ${ILCSOFT_PATH}/init_ilcsoft.sh  "export LD_LIBRARY_PATH=\${LD_LIBRARY_PATH}:${targetdir}/lib\n" )
	ENDIF()
FILE( APPEND ${ILCSOFT_PATH}/init_ilcsoft.sh  "\n" )
FILE( APPEND ${ILCSOFT_PATH}/init_ilcsoft.sh  "\n" )